# https://developers.cloudflare.com/pages/functions/wrangler-configuration/
name = "neos21-misskey"
compatibility_date = "2024-09-17"
pages_build_output_dir = "."

[[d1_databases]]
database_id = "19f6a921-41b8-4c69-b17b-f2af040ea340"
binding = "DB"
database_name = "neos21-misskey"

[[env.production.d1_databases]]
database_id = "19f6a921-41b8-4c69-b17b-f2af040ea340"
binding = "DB"
database_name = "neos21-misskey"
